[[bin]]
name = 'node-template'
path = 'src/main.rs'

[build-dependencies]
vergen = '3.0.4'

[build-dependencies.build-script-utils]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-build-script-utils'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[package]
authors = ['Anonymous']
build = 'build.rs'
edition = '2018'
name = 'node-template'
version = '2.0.0'
[profile.release]
panic = 'unwind'

[dependencies]
derive_more = '0.15.0'
exit-future = '0.1.4'
futures = '0.1.29'
log = '0.4.8'
parking_lot = '0.9.0'
tokio = '0.1.22'
trie-root = '0.15.2'

[dependencies.aura]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-aura'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.aura-primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-aura-primitives'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-basic-authorship'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.codec]
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.ctrlc]
features = ['termination']
version = '3.1.3'

[dependencies.grandpa]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-finality-grandpa'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.grandpa-primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-finality-grandpa-primitives'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.inherents]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-inherents'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.network]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-network'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.runtime]
package = 'node-template-runtime'
path = 'runtime'

[dependencies.sr-io]
git = 'https://github.com/paritytech/substrate.git'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.sr-primitives]
git = 'https://github.com/paritytech/substrate.git'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.substrate-cli]
git = 'https://github.com/paritytech/substrate.git'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.substrate-client]
git = 'https://github.com/paritytech/substrate.git'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.substrate-executor]
git = 'https://github.com/paritytech/substrate.git'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.substrate-service]
git = 'https://github.com/paritytech/substrate.git'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[dependencies.transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-transaction-pool'
rev = 'c0b1941100532d30092f1ebec268e61cf4073d07'

[workspace]
members = ['runtime']
