[package]
authors = ['Anonymous']
edition = '2018'
name = 'node-template-runtime'
version = '2.0.0'

[features]
default = ['std']
std = [
    'aura-primitives/std',
    'aura/std',
    'balances/std',
    'block-builder-api/std',
    'codec/std',
    'contracts/std',
    'executive/std',
    'grandpa/std',
    'indices/std',
    'inherents/std',
    'offchain-primitives/std',
    'primitives/std',
    'randomness-collective-flip/std',
    'rstd/std',
    'runtime-io/std',
    'safe-mix/std',
    'serde',
    'sr-api/std',
    'sr-primitives/std',
    'substrate-session/std',
    'sudo/std',
    'support/std',
    'system/std',
    'timestamp/std',
    'transaction-payment/std',
    'tx-pool-api/std',
    'version/std',
]

[build-dependencies.wasm-builder-runner]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-wasm-builder-runner'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'
version = '1.0.4'

[dependencies.aura]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-aura'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.aura-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-aura-primitives'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.balances]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.block-builder-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-block-builder-runtime-api'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.contracts]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-contracts'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.executive]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'palette-executive'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.grandpa]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-grandpa'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.indices]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-indices'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.inherents]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-inherents'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.offchain-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-offchain-primitives'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.randomness-collective-flip]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-randomness-collective-flip'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.rstd]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-std'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.runtime-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-io'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.safe-mix]
default-features = false
version = '1.0.0'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.sr-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.sr-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.substrate-session]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.sudo]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-sudo'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'palette-support'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'palette-system'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.timestamp]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-timestamp'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.transaction-payment]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-transaction-payment'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.tx-pool-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-transaction-pool-runtime-api'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'

[dependencies.version]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-version'
rev = '59b8b10b77a03baca1f4e477a12f563998e402f7'
